#!/usr/bin/env python
#
import math

gamma = 2.5
n_in  = 256
n_out = 3200

print "// Generated by gamma_tab.py, gamma %.3f" % gamma
print "//"

print "static const uint16_t gamma_tab[%d] = {" % n_in

for i in range(n_in):
    # apply gamma correction
    #
    ig = round( ( float(i) / (n_in-1) ) ** gamma * (n_out-1) )
    
    if (i % 8 == 0):
        print "   ",

    if (i != n_in-1):
        print "%4d," % ig,
    else:
        print "%4d" % ig,

    if (i % 8 == 7):
        print

print "};"
